### ISSUE TITLE
Warning: Rack::Utils::HeaderHash is deprecated and will be removed in Rack 3.1, switch to Rack::Headers

### ISSUE THREAD

**Issue by rgaufman** [savonrb/httpi#246] opened 2024-03-18 12:00 UTC
Getting this deprecation warning:

```
/opt/homebrew/lib/ruby/gems/3.3.0/gems/httpi-3.0.1/lib/httpi/request.rb:72: warning: Rack::Utils::HeaderHash is deprecated and will be removed in Rack 3.1, switch to Rack::Headers
```

**Comment by pcai** [comment] 2024-03-18 15:41
dupe of #239 addressed in [v4.0.1](https://github.com/savonrb/httpi/releases/tag/v4.0.1)

**Closed by pcai** 2024-03-18 15:41 UTC
